DjangoWorks/library/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
app_name='books'

urlpatterns = [
   path('',views.Home.as_view(),name='home'),
   path('viewbook', views.ViewBooks.as_view(), name='viewbook'),
   path('addbooks', views.AddBooks.as_view(), name='addbooks'),
   path('edit/<int:i>', views.EditView.as_view(), name='editview'),
   path('details/<int:i>', views.DetailsView.as_view(), name='detailview'),
   path('delete/<int:i>', views.DeleteView.as_view(), name='deleteview'),
]

DjangoWorks/library/library/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('users/', include('users.urls'))

]
from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

DjangoWorks/library/users/urls.py
from django.contrib import admin
from django.urls import path
from users import views
app_name='users'

urlpatterns = [
    path('register',views.Register.as_view(),name='register'),
    path('login',views.Login.as_view(),name='login'),
]

DjangoWorks/library/books/models.py
from django.db import models

class Book(models.Model):
    title=models.CharField(max_length=40)
    author=models.CharField(max_length=30)
    price=models.IntegerField()
    page=models.IntegerField()
    language=models.CharField(max_length=20)
    image=models.ImageField(upload_to='images')

DjangoWorks/library/books/forms.py
from django import forms

# class Addbook(forms.Form):
#     title=forms.CharField()
#     author=forms.CharField()
#     price=forms.IntegerField()
#     pages=forms.IntegerField()
#     language=forms.CharField()
#
from books.models import Book     # defines form based on model
class Addbook(forms.ModelForm):
    class Meta:
        model=Book
        fields="__all__"

DjangoWorks/library/books/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views import View
from books.forms import Addbook
from books.models import Book
class Home(View):
    def get(self,request):
        return render(request,'home.html')

class ViewBooks(View):
    def get(self,request):
        b=Book.objects.all()
        context={'books':b}
        return render(request, 'viewbooks.html',context)

class AddBooks(View):
    def get(self,request):
        form_instance=Addbook()
        context = {'form': form_instance}
        return render(request,'addbooks.html',context)
    def post(self,request):
        form_instance=Addbook(request.POST,request.FILES)
        if form_instance.is_valid():
            # data=form_instance.cleaned_data
            # print(data)
            # t = data['title']
            # a = data['author']
            # p = data['price']
            # pg = data['pages']
            # l = data['language']
            # b=Book.objects.create(title=t,author=a,price=p,page=pg,language=l)
            # b.save()
            form_instance.save()
            return render(request,'addbooks.html')

class EditView(View):
    def post(self,request,i):
        b=Book.objects.get(id=i)
        form_instance=Addbook(request.POST,request.FILES,instance=b)
        if form_instance.is_valid():
            form_instance.save()
            return redirect('books:viewbook')
    def get(self,request,i):
        b=Book.objects.get(id=i)
        form_instance = Addbook(instance=b)
        context = {'form': form_instance}
        return render(request,'edit.html',context)

class DetailsView(View):
    def get(self, request,i):
        # print(i)
        b=Book.objects.get(id=i)  #dynamic routing
        context={'book':b}
        return render(request, 'details.html',context)

class DeleteView(View):
    def get(self,request,i):
        print(i)
        b=Book.objects.get(id=i)
        b.delete()
        return redirect('books:viewbooks')

DjangoWorks/library/users/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View


class Register(View):
    def get(self,request):
        return render(request,'register.html')

class Login(View):
    def get(self,request):
        return render(request,'login.html')

DjangoWorks/library/templates/addbooks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%extends 'base.html' %}
{%block contents %}
{% load crispy_forms_tags %}
<h1 style="text-align:center;padding:30px;">Add  Books</h1>
<div class="p-4 border border-black m-3">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
     <input type="submit" class="btn btn-success d-flex justify-content-center">
</form>
</div>
{%endblock %}
</body>
</html>

DjangoWorks/library/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body style="background-color:#E5E9C5;">
<nav class="navbar navbar-expand-lg " style="background-color:#016B61;padding:20px;color:white;">
  <div class="container">
    <a class="navbar-brand text-white fw-bold fs-3" href="#">Library</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'books:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'books:viewbook' %}">Viewbook</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white"  href="{% url 'books:addbooks' %}">Addbook</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{% url 'users:register' %}">Register</a>
        </li>
      </ul>

    </div>
  </div>
</nav>
{% block contents %}

{%endblock%}
</body>
</html>

DjangoWorks/library/templates/details.html
{% extends 'base.html' %}
{% block contents %}
<div class="container p-4 m-3 ">
<table class="table table-bordered">
    <h1 class="text-center text-success">Books data</h1>
    <tr>
        <th>Title</th>
        <td>{{book.title}}</td>
    </tr>
        <tr>
        <th>Author</th>
        <td>{{book.author}}</td>
    </tr>
        <tr>
        <th>Page</th>
        <td>{{book.page}}</td>
    </tr>
        <tr>
        <th>Price</th>
        <td>{{book.price}}</td>
    </tr>
</table>
</div>
{% endblock %}

DjangoWorks/library/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
</head>
<body>
{%extends 'base.html' %}
{%block contents %}
{% load crispy_forms_tags %}
<h1 style="text-align:center;padding:30px;">Edit Books</h1>
<div class="p-4 border border-black m-3">
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
     <input type="submit" class="btn btn-success d-flex justify-content-center">
</form>
</div>
{%endblock %}
</body>
</html>

DjangoWorks/library/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
{% extends 'base.html' %}
{%block contents %}
<h1 style="text-align:center;padding:30px;">Home Page</h1>
{%endblock %}
</body>
</html>

DjangoWorks/library/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%extends 'base.html' %}
{%block contents %}
<h1 style="text-align:center;padding:30px;">Login Page</h1>
{%endblock %}
</body>
</html>

DjangoWorks/library/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%extends 'base.html' %}
{%block contents %}
<h1 style="text-align:center;padding:30px;">Register Page</h1>
{%endblock %}
</body>
</html>

DjangoWorks/library/templates/viewbooks.html
{%extends 'base.html' %}
{%block contents %}
<h1 style="text-align:center;padding:30px;">View Books</h1>
<!--<div class="m-4 p-4 fs-1">-->
<!--{% for i in books %}-->
<!--<p> Title : {{i.title}}</p>-->
<!--<p> Author : {{i.author}} </p>-->
<!--<p>Price : {{i.price}} </p>-->
<!--<br>-->
<!--{%endfor%}-->
<!--</div>-->
<div class="p-4 m-4">
<table class="table table-bordered">
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Price</th>
        <th>Pages</th>
        <th>Image
        <th>Actions</th>
    </tr>
    {% for i in books %}
    <tr>
        <td> {{i.title}}</td>
        <td> {{i.author}}</td>
        <td> {{i.page}}</td>
        <td> {{i.price}}</td>
        <td><img src="{{i.image.url}}" width="100px" height="100px"/></td>
        <td ><a href="{% url 'books:detailview' i.id %}" class="btn btn-danger m-3">Details</a>
            <a href="{% url 'books:editview' i.id %}" class="btn btn-danger m-3">Edit</a>
            <a href="{% url 'books:deleteview' i.id%}" class="btn btn-danger m-3">Delete</a></td>
    </tr>
    {% endfor %}
</table>
</div>
{%endblock %}